events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        # Настраиваем прослушивание 81 порта по ТЗ
        listen 81;
        server_name localhost;

        location / {
            # Передаем запрос нашему FastCGI-серверу
            fastcgi_pass 127.0.0.1:8080;
            
            # Подключаем стандартные системные параметры FastCGI
            include /etc/nginx/fastcgi_params;
        }
    }
}
